baseURL: "https://willnorris.com/"
languageCode: "en-us"
title: "willnorris.com"

params:
  description: "there's more to life than this"
  author:
    name: "Will Norris"
    url: "https://willnorris.com/"
    photo: "/logo.jpg"
    twitter: "@willnorris"
  twitter_card: "summary"
  twitter: "@willnorris"

disableHugoGeneratorInject: true

permalinks:
  posts: "/:year/:month/:filename/"

# disable taxonomy pages
taxonomies: []

markup:
  highlight:
    codeFences: false
    style: friendly

mediaTypes:
  application/atom+xml:
    suffixes: [xml]

outputFormats:
  atom:
    basename: atom
    isPlainText: false
    mediaType: application/atom+xml

outputs:
  home: [html, atom]
  section: [html]
