baseURL: "https://willnorris.com/"
languageCode: "en-us"
title: "willnorris.com"

params:
  description: "don't lose focus"
  author:
    name: "Will Norris"
    url: "https://willnorris.com/"
    photo: "/logo.jpg"
    twitter: "@willnorris"
  twitter_card: "summary_large_image"
  twitter: "@willnorris"
  headerMeta: false
  breadcrumbs: false
  gitInfo: false
  pageHistoryURL: https://github.com/willnorris/willnorris.com/commits/main/content/%v
  pageSourceURL: https://github.com/willnorris/willnorris.com/blob/main/content/%v?plain=1
  short_baseurl: "https://wjn.me/"
  imageproxy:
    url: /api/imageproxy/
    default_baseurl: https://willnorris.com/

security:
  funcs:
    getenv:
      - ^IMAGEPROXY_

permalinks:
  posts: "/:year/:filename/"

enableGitInfo: true
frontmatter:
  date:
    - date
    - publishDate
    - lastmod
    - :git
    - :fileModTime
  lastmod:
    - :git
    - :fileModTime
    - :default

# disable taxonomy pages
taxonomies: []

markup:
  goldmark:
    extensions:
      footnote: true
      linkify: false
    parser:
      attribute:
        block: true
        headline: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    noClasses: false
    style: friendly

mediaTypes:
  application/atom+xml:
    suffixes: [xml]

outputFormats:
  atom:
    basename: atom
    isPlainText: false
    mediaType: application/atom+xml

outputs:
  home: [html, atom]
  section: [html]
