baseURL = "https://willnorris.com/"
languageCode = "en-us"
title = "willnorris.com"

enableGitInfo = true
summaryLength = 30

# disable taxonomy pages
taxonomies = []

[params]
  description = "don't lose focus"
  twitter_card = "summary_large_image"
  twitter = "@willnorris"
  headerMeta = false
  breadcrumbs = false
  gitInfo = false
  pageHistoryURL = "https://github.com/willnorris/willnorris.com/commits/main/content/%v"
  pageSourceURL = "https://github.com/willnorris/willnorris.com/blob/main/content/%v?plain=1"
  short_baseurl = "https://wjn.me/"

  [params.author]
    name = "Will Norris"
    url = "https://willnorris.com/"
    photo = "/logo.jpg"
    twitter = "@willnorris"

  [params.imageproxy]
    url = "/api/imageproxy/"
    default_baseurl = "https://willnorris.com/"

[security]
  [security.exec]
    osEnv = [
        # default from https://gohugo.io/about/security-model/#security-policy
        '(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$',
        # asdf vars for development environment
        '^ASDF_\w+$',
    ]
  [security.funcs]
    getenv = ['^IMAGEPROXY_']

[permalinks]
  posts = "/:year/:filename/"

[frontmatter]
  date = [ "date", "publishDate", "lastmod", ":git", ":fileModTime" ]
  lastmod = [ ":git", ":fileModTime", ":default" ]

[markup.goldmark]
  [markup.goldmark.extensions]
    linkify = false
    extras.subscript.enable = true
    extras.superscript.enable = true
  [markup.goldmark.parser.attribute]
    block = true
  [markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
  codeFences = true
  noClasses = false
  style = "friendly"

[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.atom]
  basename = "atom"
  isPlainText = false
  mediaType = "application/atom+xml"

[outputs]
  home = ["html", "atom"]
  section = ["html"]

[build.buildStats]
  enable = true
