# Site settings
name: willnorris.com
description: there's more to life than this
url: http://willnorris.dev
short_baseurl: http://willnorris.dev
twitter: "@willnorris"
include:
  - .well-known

collections:
  go_packages:
    output: true
    permalink: /go/:path
  redirects:
    output: true
    permalink: /_/:path
  wiki:
    output: true
    permalink: /wiki/:path

defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: Will Norris
        url: https://willnorris.com/
        photo: /logo.jpg
        twitter: "@willnorris"
        google_plus: +willnorris
      twitter_card: summary
      webmention_endpoint: /api/webmention
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
  -
    scope:
      path: ""
      type: go_packages
    values:
      layout: go-package
  -
    scope:
      path: ""
      type: redirects
    values:
      layout: redirect
  -
    scope:
      path: ""
      type: wiki
    values:
      layout: page

# Build settings
source: src
destination: public

highlighter: false
permalink: /:year/:month/:title

sass:
  sass_dir: css
  style: :compressed

markdown: kramdown
kramdown:
  input: GFM
  auto_id_stripping: true
  enable_coderay: false
  hard_wrap: false

plugins:
  - jekyll-default-layout
