baseURL: "https://willnorris.com/"
languageCode: "en-us"
title: "willnorris.com"

params:
  description: "there's more to life than this"
  author:
    name: "Will Norris"
    url: "https://willnorris.com/"
    photo: "/logo.jpg"

disableHugoGeneratorInject: true

permalinks:
  posts: "/:year/:month/:title/"

menu:
  main:
    - identifier: about
      name: about
      url: /about/
