baseURL: "https://willnorris.com/"
languageCode: "en-us"
title: "willnorris.com"

params:
  description: "there's more to life than this"
  author:
    name: "Will Norris"
    url: "https://willnorris.com/"
    photo: "/logo.jpg"
  short_baseurl: "https://wjn.me/"

disableHugoGeneratorInject: true

permalinks:
  posts: "/:year/:month/:title/"

# disable taxonomy pages
taxonomies: []

mediaTypes:
  application/atom+xml:
    suffixes: [xml]

outputFormats:
  atom:
    basename: atom
    isPlainText: false
    mediaType: application/atom+xml

outputs:
  home: [html, atom]
  section: [html]
