FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base AS build
RUN apk update && apk add build-base git openssh go-1.25

WORKDIR /work

COPY go.mod go.sum ./
RUN go mod download

COPY . .
ARG TARGETOS TARGETARCH
RUN GOOS=${TARGETOS} GOARCH="${TARGETARCH}" CGO_ENABLED=0 go build -v ./cmd/caddy &&\
  GOOS=${TARGETOS} GOARCH="${TARGETARCH}" CGO_ENABLED=1 go build -v --tags extended ./cmd/hugo

# Final image is node:slim image with git installed
# and with caddy and hugo binaries added.
# This contains everything needed to rebuild and serve the site.
FROM node:26-slim

RUN apt -y update && apt install -y --no-install-recommends git && apt clean

COPY --from=build /work/caddy /caddy
COPY --from=build /work/hugo /hugo

ENTRYPOINT ["/caddy"]
CMD []
