app = "willnorris-go"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "ghcr.io/tailscale/golink:main"

[[mounts]]
  source = "willnorris_go_data"
  destination = "/home/nonroot"
