name: webmentions

on:
  workflow_dispatch:
  repository_dispatch:
    types: [webmention]
  schedule:
    # daily at 02:17
    - cron: "17 2 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: fetch webmentions
        env:
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
        run: go run ./cmd/mentions

      - name: create pull request
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6.0.2
        with:
          branch: automation/webmentions
          delete-branch: true
          commit-message: inbound webmentions
          author: webmentions-sync <indieweb@users.noreply.github.com>
          title: inbound webmentions
          labels: |
            webmentions
          reviewers: willnorris
          body: ""
