name: webmentions

on:
  workflow_dispatch:
  repository_dispatch:
    types: [webmention]
  schedule:
    - cron: "17 2 * * *"

jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm install

      - name: fetch webmentions
        env:
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
        run: node ./tools/store-webmentions.mjs

      - name: create pull request
        uses: peter-evans/create-pull-request@9825ae65b1cb54b543b938503728b432a0176d29 # v3.10.0
        with:
          commit-message: update webmentions
          branch: automation/webmentions
          title: update webmentions
          body:
