name: webmentions

on:
  workflow_dispatch:
  repository_dispatch:
    types: [webmention]
  schedule:
    # daily at 02:17
    - cron: "17 2 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci

      - name: fetch webmentions
        env:
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
        run: node ./tools/store-webmentions.mjs

      - name: create pull request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          branch: automation/webmentions
          delete-branch: true
          commit-message: inbound webmentions
          author: webmentions-sync <indieweb@users.noreply.github.com>
          title: inbound webmentions
          labels: |
            webmentions
          reviewers: willnorris
          body:
